from django.urls import path

from .views import (
    AddressDetailAPIView,
    AddressListCreateAPIView,
    CategoryDetailAPIView,
    CategoryListCreateAPIView,
    ChatAPIView,
    CouponValidateAPIView,
    LoginAPIView,
    LogoutAPIView,
    MeAPIView,
    OrderCancelAPIView,
    OrderConfirmPaymentAPIView,
    OrderDetailAPIView,
    OrderListCreateAPIView,
    OrderPayAPIView,
    ProductDetailAPIView,
    ProductListAPIView,
    RegisterAPIView,
    ReviewListCreateAPIView,
    StripeWebhookView,
)

urlpatterns = [
    path("products/", ProductListAPIView.as_view(), name="product-list"),
    path("products/<slug:slug>/", ProductDetailAPIView.as_view(), name="product-detail"),
    path(
        "products/<int:product_pk>/reviews/",
        ReviewListCreateAPIView.as_view(),
        name="product-review-list",
    ),
    path("categories/", CategoryListCreateAPIView.as_view(), name="category-list"),
    path(
        "categories/<int:pk>/",
        CategoryDetailAPIView.as_view(),
        name="category-detail",
    ),
    path("addresses/", AddressListCreateAPIView.as_view(), name="address-list"),
    path("addresses/<int:pk>/", AddressDetailAPIView.as_view(), name="address-detail"),
    path("orders/", OrderListCreateAPIView.as_view(), name="order-list"),
    path("orders/<int:pk>/", OrderDetailAPIView.as_view(), name="order-detail"),
    path("orders/<int:pk>/pay/", OrderPayAPIView.as_view(), name="order-pay"),
    path(
        "orders/<int:pk>/confirm_payment/",
        OrderConfirmPaymentAPIView.as_view(),
        name="order-confirm-payment",
    ),
    path("orders/<int:pk>/cancel/", OrderCancelAPIView.as_view(), name="order-cancel"),
    path("coupons/validate/", CouponValidateAPIView.as_view(), name="coupon-validate"),
    path("auth/register/", RegisterAPIView.as_view(), name="auth-register"),
    path("auth/login/", LoginAPIView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutAPIView.as_view(), name="auth-logout"),
    path("auth/me/", MeAPIView.as_view(), name="auth-me"),
    path("stripe/webhook/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("chat/", ChatAPIView.as_view(), name="chat"),
]
