/**
 * App types. Bindings (DB, ASSETS, AUTH_LIMITER, PBKDF2_ITERATIONS) are
 * generated by `npx wrangler types` from wrangler.jsonc into
 * worker-configuration.d.ts as Cloudflare.Env — not maintained here by hand.
 */

export interface AuthUser {
  id: number;
  username: string;
}

export interface Variables {
  /** null = anonymous. Anonymous is allowed for /api/predict (no login needed). */
  user: AuthUser | null;
}

/**
 * SENTRY_DSN is intentionally NOT declared as a var in wrangler.jsonc —
 * Cloudflare rejects a var and secret of the same name. It lives only as a
 * secret (`wrangler secret put SENTRY_DSN`), so we add its type by hand. Unset
 * = Sentry disabled (errors still go to Workers Logs + D1). Each project uses
 * its OWN Sentry project/DSN, so d2t_detect and pixel-pantry stay separate.
 */
export type Bindings = Cloudflare.Env & {
  readonly SENTRY_DSN?: string;
};

export type AppEnv = { Bindings: Bindings; Variables: Variables };
