/**
 * App types. Bindings (DB, ASSETS, AUTH_LIMITER, PBKDF2_ITERATIONS) are
 * generated by `npx wrangler types` from wrangler.jsonc into
 * worker-configuration.d.ts as Cloudflare.Env — not maintained here by hand.
 */

export interface AuthUser {
  id: number;
  username: string;
}

export interface Variables {
  /** null = anonymous. Anonymous is allowed for /api/predict (no login needed). */
  user: AuthUser | null;
}

export type Bindings = Cloudflare.Env;

export type AppEnv = { Bindings: Bindings; Variables: Variables };
